#model_context_window = 1050000
#model_auto_compact_token_limit = 850000

[mcp_servers.chrome-devtools-headed]
command = "npx"
args = [
  "-y",
  "chrome-devtools-mcp@latest",
  "--autoConnect",
]
default_tools_approval_mode = "approve"

[agents]
max_threads = 10
max_depth = 1